---

- name: ansible playbook
  hosts: '{{ hosts }}'
  remote_user: vagrant
  become: yes
  vars:
    user_name: 'wanghao'
    hosts: all
  tasks:
    - include: test.yml
    - name: ssh key auth
      authorized_key:
        user: vagrant
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        state: present
    - name: 安装 epel 仓库
      yum:
        name: epel-release
        state: latest
    - name: 常用工具
      yum:
        name: '{{ item.name }}'
        state: '{{ item.state }}'
      with_items:
        - { name: tree, state: latest }
        - { name: zip, state: latest }
      tags:
        - common
    - name: 添加用户
      user:
        name: '{{ user_name }}'
        state: present
        groups: wheel
        append: yes
        password: '$6$rounds=656000$Q9VgbXrAzyMOi.YK$Xp3hd4lKs6xlpK0ZFBlU7GEOI1QPuXxifA1EAadWQvxz9l7mr6gHVLPpk2rMmB7I8frQB47NMpGiMhtPztVgG.'
      tags:
        - user
  roles:
    - docker
