---

- name: ansible playbook
  hosts: '{{ hosts }}'
  remote_user: vagrant
  become: yes
  vars:
    user_name: 'wanghao'
    hosts: all
  tasks:
    - name: 测试连接
      ping:
      tags:
        - test
    - name: ssh key auth
      authorized_key:
        user: vagrant
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        state: present
    - name: 安装 epel 仓库
      yum:
        name: epel-release
        state: latest
    - name: 添加 docker 仓库
      copy:
        src: ./files/docker-testing.repo
        dest: /etc/yum.repos.d/
    - name: 安装 docker
      yum:
        name: docker-engine
        state: latest
    - name: 启动 docker
      service:
        name: docker
        state: started
        enabled: true
    - name: 配置 docker 服务
      copy:
        src: ./files/docker.service
        dest: /etc/systemd/system/
      notify:
        - 重启 systemd
        - 重启 docker
    - name: 添加用户
      user:
        name: '{{ user_name }}'
        state: present
        groups: wheel
        append: yes
        password: '$6$rounds=656000$Q9VgbXrAzyMOi.YK$Xp3hd4lKs6xlpK0ZFBlU7GEOI1QPuXxifA1EAadWQvxz9l7mr6gHVLPpk2rMmB7I8frQB47NMpGiMhtPztVgG.'
      tags:
        - user

  handlers:
    - name: 重启 systemd
      command: /usr/bin/systemctl daemon-reload
    - name: 重启 docker
      service:
        name: docker
        state: restarted
