---

- name: ansible playbook
  hosts: all
  remote_user: vagrant
  become: yes
  tasks:
    - name: 测试连接
      ping:
    - name: ssh key auth
      authorized_key:
        user: vagrant
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        state: present
    - name: 安装 epel 仓库
      yum:
        name: epel-release
        state: latest
    - name: 添加 docker 仓库
      copy:
        src: ./files/docker-testing.repo
        dest: /etc/yum.repos.d/
    - name: 安装 docker
      yum:
        name: docker-engine
        state: latest
    - name: 启动 docker
      service:
        name: docker
        state: started
        enabled: true
